#!/bin/bash
touch temp.text
lsof -n -i4TCP:$1 | awk '{print $2}' > temp.text
pidToStop=`(sed '2q;d' temp.text)`
> temp.text
if [[ -n $pidToStop ]]
then
kill -9 $pidToStop
echo "Done. Services running on port $1 has stopped."
else
echo "Sorry, there is nothing running on port $1"
fi
rm temp.text
